"""Add app location for deployments

Revision ID: 49437c661c80
Revises: f027333560c0
Create Date: 2021-04-12 14:32:50.280249+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49437c661c80"
down_revision = "f027333560c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("app_location", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "app_location")
    # ### end Alembic commands ###
