"""Add stage failed at to build table


Revision ID: fd47bf4df408
Revises: 1a6b414dc6ca
Create Date: 2021-09-17 20:01:12.036035+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd47bf4df408"
down_revision = "1a6b414dc6ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("builds", sa.Column("failed_at_stage", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("builds", "failed_at_stage")
    # ### end Alembic commands ###
