ARG TAG
FROM distributed

ENV CELERY_BROKER_URL redis://redis-master/0
ENV CELERY_RESULT_BACKEND redis://redis-master/0

ENV HOST 0.0.0.0
ENV PORT 5050
ENV DEBUG true

ENV IS_FLASK True

# expose the app port
EXPOSE 80
EXPOSE 5050

RUN pip install -r requirements.txt

COPY ./api /home/api
COPY ./api/endpoints.py /home/api
COPY ./setup.py /home
RUN cd /home && pip install -e .

WORKDIR /home/api

# run the app server
CMD ["gunicorn", "--bind", "0.0.0.0:5050", "api:app", "--access-logfile", "-"]
