ARG TAG
FROM comporg/celerybase

# install packages here
# install packages necessary for celery,
RUN pip install -r requirements.txt
# Edit Dockerfile here for installing necessary packages, copying files, etc.
######################
RUN conda install -c pslmodels "taxbrain>=0.2.2" pip
RUN pip install boto3
######################


# copy over necessary files for this project's celery app
COPY ./api/__init__.py /home/distributed/api/__init__.py
COPY ./api/celery_app/__init__.py /home/distributed/api/celery_app/__init__.py
COPY ./api/celery_app/pslmodels_taxbrain_tasks.py /home/distributed/api/celery_app/pslmodels_taxbrain_tasks.py
COPY ./setup.py /home/distributed
RUN cd /home/distributed && pip install -e .

WORKDIR /home/distributed/api

ENTRYPOINT celery -A celery_app.pslmodels_taxbrain_tasks worker --loglevel=info --concurrency=1 -Q pslmodels_taxbrain_queue -n pslmodels_taxbrain_sim@%h
