# Generated by Django 2.1.5 on 2019-01-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_project_sponsor'),
        ('matchups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupsrun',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_matchupsrun_sponsored_runs', to='users.Profile'),
        ),
    ]
