# Generated by Django 2.1.5 on 2019-01-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0002_matchupsrun_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupsrun',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchups_matchupsrun_runs', to='users.Profile'),
        ),
    ]
