# Generated by Django 2.1.3 on 2018-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compbaseball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compbaseballinputs',
            name='use_2018',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
