# Generated by Django 2.1.4 on 2019-01-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compbaseball', '0002_compbaseballinputs_use_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compbaseballrun',
            name='inputs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='compbaseball.CompbaseballInputs'),
        ),
    ]
