from .views import (
    ModelPageView,
    NewSimView,
    EditSimView,
    OutputsDownloadView,
    OutputsView,
    PermissionPendingView,
    PermissionGrantedView,
    DataView,
    VizView,
    EmbedView,
)

from .api import (
    InputsAPIView,
    CreateAPIView,
    DetailAPIView,
    RemoteDetailAPIView,
    ForkDetailAPIView,
    OutputsAPIView,
    DetailMyInputsAPIView,
    MyInputsAPIView,
    ModelConfigAPIView,
    NewSimulationAPIView,
    AuthorsAPIView,
    AuthorsDeleteAPIView,
    SimulationAccessAPIView,
    UserSimsAPIView,
    PublicSimsAPIView,
    ProfileSimsAPIView,
)
