# Generated by Django 2.1.7 on 2019-03-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0002_auto_20190316_1512")]

    operations = [
        migrations.RemoveField(model_name="charge", name="customer"),
        migrations.RemoveField(model_name="invoice", name="charge"),
        migrations.RemoveField(model_name="invoice", name="customer"),
        migrations.RemoveField(model_name="invoice", name="subscription"),
        migrations.RemoveField(model_name="event", name="charge"),
        migrations.RemoveField(model_name="event", name="invoice"),
        migrations.AddField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[("primary", "Primary")], default="primary", max_length=50
            ),
        ),
        migrations.DeleteModel(name="Charge"),
        migrations.DeleteModel(name="Invoice"),
    ]
