# Generated by Django 2.1.7 on 2019-03-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("billing", "0003_auto_20190321_1749")]

    operations = [
        migrations.AlterField(
            model_name="subscriptionitem",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_items",
                to="billing.Plan",
            ),
        )
    ]
