# Generated by Django 3.0.3 on 2020-03-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0004_auto_20190322_1010")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("compute-studio", "Compute Studio Subscription"),
                ],
                default="primary",
                max_length=50,
            ),
        )
    ]
