# Generated by Django 3.0.10 on 2020-09-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_auto_20200306_1600"),
    ]

    operations = [
        migrations.DeleteModel(name="UsageRecord",),
    ]
