# Generated by Django 3.0.10 on 2020-12-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_delete_usagerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255, unique=True)),
                (
                    "amount_off",
                    models.IntegerField(
                        blank=True,
                        help_text="Amount (as decimal) that will be taken off the subtotal of any invoices for this customer.",
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, choices=[("usd", "usd")], max_length=3, null=True
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("Once", "once"),
                            ("Multi-month", "multi-month"),
                            ("Forever", "forever"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "duration_in_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("name", models.TextField(blank=True, default="", max_length=5000)),
                (
                    "percent_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
    ]
