# Generated by Django 2.1.7 on 2019-03-21 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("comp", "0002_auto_20190316_1512")]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="exp_comp_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
