# Generated by Django 2.1.7 on 2019-03-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("comp", "0003_auto_20190321_1505")]

    operations = [
        migrations.AlterField(
            model_name="inputs",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sim_params",
                to="users.Project",
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sims",
                to="users.Profile",
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sims",
                to="users.Project",
            ),
        ),
    ]
