# Generated by Django 2.1.7 on 2019-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comp", "0004_auto_20190322_1238")]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="model_pk",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        )
    ]
