# Generated by Django 2.1.7 on 2019-04-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0005_simulation_model_pk")]

    operations = [
        migrations.RenameField(
            model_name="simulation", old_name="error_text", new_name="traceback"
        )
    ]
