# Generated by Django 2.2 on 2019-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comp", "0006_auto_20190409_1316")]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAIL", "Fail"),
                    ("WORKER_FAILURE", "Worker Failure"),
                ],
                default="SUCCESS",
                max_length=20,
            ),
            preserve_default=False,
        )
    ]
