# Generated by Django 2.2.1 on 2019-05-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0007_simulation_status")]

    operations = [
        migrations.RenameField(
            model_name="simulation", old_name="model_vers", new_name="model_version"
        )
    ]
