# Generated by Django 2.2.1 on 2019-05-16 21:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0008_auto_20190514_1157")]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="errors_warnings",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        )
    ]
