# Generated by Django 2.2.1 on 2019-05-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0008_auto_20190514_1157")]

    operations = [
        migrations.RenameField(
            model_name="inputs",
            old_name="errors_warnings_text",
            new_name="errors_warnings",
        )
    ]
