# Generated by Django 2.2.1 on 2019-05-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0009_auto_20190517_0708")]

    operations = [
        migrations.RenameField(
            model_name="inputs", old_name="model_parameters", new_name="adjustment"
        )
    ]
