# Generated by Django 2.2.1 on 2019-07-16 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_project_listed"),
        ("comp", "0010_auto_20190522_0846"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputs",
            name="job_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="inputs",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inputs",
                to="users.Profile",
            ),
        ),
        migrations.AddField(
            model_name="inputs",
            name="traceback",
            field=models.CharField(
                blank=True, default=None, max_length=4000, null=True
            ),
        ),
    ]
