# Generated by Django 2.2.1 on 2019-07-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comp", "0012_inputs_status")]

    operations = [
        migrations.AddField(
            model_name="inputs",
            name="client",
            field=models.CharField(
                choices=[
                    ("web-alpha", "Web-Alpha"),
                    ("web-beta", "Web-Beta"),
                    ("rest-api", "REST API"),
                ],
                default="web-alpha",
                max_length=32,
            ),
            preserve_default=False,
        )
    ]
