# Generated by Django 2.2.5 on 2019-10-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0015_auto_20190928_0840")]

    operations = [
        migrations.RenameField(
            model_name="inputs", old_name="inputs_file", new_name="custom_adjustment"
        )
    ]
