# Generated by Django 2.2.7 on 2019-11-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("comp", "0018_auto_20191125_1134")]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="inputs",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sim",
                to="comp.Inputs",
            ),
        )
    ]
