# Generated by Django 3.0.2 on 2020-01-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0020_simulation_is_public")]

    operations = [migrations.RemoveField(model_name="simulation", name="readme")]
