# Generated by Django 3.0.2 on 2020-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comp", "0022_simulation_readme")]

    operations = [
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.UniqueConstraint(
                fields=("project", "model_pk"), name="unique_model_pk"
            ),
        )
    ]
