# Generated by Django 3.0.2 on 2020-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comp", "0023_auto_20200122_1050")]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="notify_on_completion",
            field=models.BooleanField(default=False),
        )
    ]
