# Generated by Django 3.0.2 on 2020-01-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_project_pay_per_sim"),
        ("comp", "0023_auto_20200122_1050"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="authors",
            field=models.ManyToManyField(
                related_name="authored_sims", to="users.Profile"
            ),
        )
    ]
