# Generated by Django 3.0.2 on 2020-01-24 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import webapp.apps.comp.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_project_pay_per_sim"),
        ("comp", "0024_simulation_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_name",
                    models.CharField(
                        choices=[("add_author", "Permission to add author.")],
                        max_length=32,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        default=webapp.apps.comp.models.two_days_from_now
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_permissions",
                        to="users.Profile",
                    ),
                ),
                (
                    "sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_permissions",
                        to="comp.Simulation",
                    ),
                ),
            ],
        )
    ]
