# Generated by Django 3.0.3 on 2020-02-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comp", "0025_auto_20200213_1813")]

    operations = [
        migrations.AlterModelOptions(
            name="simulation",
            options={
                "permissions": (
                    (
                        "read_simulation",
                        "Users with this permission may view this simulation, even if it's private.",
                    ),
                    (
                        "write_simulation",
                        "Users with this permission may edit the title, description, and simulation parameters.",
                    ),
                    (
                        "admin_simulation",
                        "Users with this permission control the visibility of this simulation and who has read, write, and admin access to it.",
                    ),
                )
            },
        )
    ]
