# Generated by Django 3.0.3 on 2020-04-06 20:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webapp.apps.comp.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200319_0854"),
        ("comp", "0026_auto_20200221_1228"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inputs_version",
                    models.CharField(choices=[("v1", "Version 1")], max_length=10),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "meta_parameters_values",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                ("meta_parameters", webapp.apps.comp.models.JSONField(default=dict)),
                ("model_parameters", webapp.apps.comp.models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_configs",
                        to="users.Project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inputs",
            name="model_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inputs_instances",
                to="comp.ModelConfig",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelconfig",
            constraint=models.UniqueConstraint(
                fields=("project", "model_version", "meta_parameters_values"),
                name="unique_model_config",
            ),
        ),
    ]
