# Generated by Django 3.0.10 on 2020-09-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20200906_1719"),
        ("comp", "0027_auto_20200406_1547"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sims",
                to="users.Tag",
            ),
        ),
    ]
