# Generated by Django 3.0.13 on 2021-03-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comp", "0028_simulation_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="job_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("STARTED", "Started"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("INVALID", "Invalid"),
                    ("FAIL", "Fail"),
                    ("WORKER_FAILURE", "Worker Failure"),
                ],
                default="SUCCESS",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
