# Generated by Django 3.2.8 on 2021-10-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comp", "0029_auto_20210321_2247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputs",
            name="adjustment",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="inputs",
            name="custom_adjustment",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="inputs",
            name="errors_warnings",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="inputs",
            name="gui_inputs",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="inputs",
            name="meta_parameters",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="inputs",
            name="raw_gui_inputs",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="modelconfig",
            name="meta_parameters_values",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="aggr_outputs",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="meta_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="outputs",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="readme",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
