# Generated by Django 2.1 on 2018-09-20 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoutput',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Project'),
        ),
        migrations.AddField(
            model_name='fileoutput',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
