import * as React from "react";
import ReactLoading from "react-loading";
import {
  Card,
  Row,
  Col,
  OverlayTrigger,
  Tooltip,
  Modal,
  Button
} from "react-bootstrap";
import * as moment from "moment";
import {
  RemoteOutputs,
  Outputs,
  SimAPIData,
  Output,
  TableOutput,
  BokehOutput
} from "./types";

interface OutputsProps {
  fetchRemoteOutputs: () => Promise<SimAPIData<RemoteOutputs>>;
  fetchOutputs: () => Promise<SimAPIData<Outputs>>;
}

type OutputsState = Readonly<{
  remoteSim: SimAPIData<RemoteOutputs>;
  sim: SimAPIData<Outputs>;
}>;

const Table: React.FC<{ output: TableOutput }> = ({ output }) => (
  <div
    dangerouslySetInnerHTML={{ __html: output.data }} // needs to be sanitized somehow.
    className="card publish markdown"
  />
);

const Bokeh: React.FC<{ output: BokehOutput }> = ({ output }) => (
  <div>
    <div
      dangerouslySetInnerHTML={{
        __html: output.data.html + " " + output.data.javascript
      }}
    ></div>
  </div>
);

const OutputModal: React.FC<{
  output: Output | BokehOutput | TableOutput;
  children: JSX.Element;
}> = ({ output, children }) => {
  const [show, setShow] = React.useState(false);

  let el;
  switch (output.media_type) {
    case "table":
      el = <Table output={output as TableOutput} />;
      break;
    case "bokeh":
      console.log("bokeh", output);
      el = <Bokeh output={output as BokehOutput} />;
      break;
    default:
      el = <div dangerouslySetInnerHTML={{ __html: output.data }} />;
  }

  return (
    <>
      <Button variant="outline-primary" onClick={() => setShow(true)}>
        {children}
      </Button>
      <Modal show={show} onHide={() => setShow(false)} size="xl">
        <Modal.Header closeButton>
          <Modal.Title>{output.title}</Modal.Title>
        </Modal.Header>
        <Modal.Body>{el}</Modal.Body>
        <Modal.Footer>
          <Button variant="outline-primary" onClick={() => setShow(false)}>
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
};

export default class OutputsComponent extends React.Component<
  OutputsProps,
  OutputsState
> {
  constructor(props) {
    super(props);
    this.state = {
      remoteSim: null,
      sim: null
    };
  }

  componentDidMount() {
    this.props.fetchRemoteOutputs().then(data => {
      this.setState({ remoteSim: data });
    });
    this.props.fetchOutputs().then(data => {
      this.setState({ sim: data });
    });
  }

  render() {
    if (!this.state.remoteSim) {
      return (
        <Card className="card-outer">
          <Card.Body>
            <div className="d-flex justify-content-center">
              <ReactLoading type="spokes" color="#2b2c2d" />
            </div>
          </Card.Body>
        </Card>
      );
    }
    let creation_date = moment(this.state.remoteSim.creation_date).format(
      "MMMM Do YYYY, h:mm:ss a"
    );
    let model_version = this.state.remoteSim.model_version;
    let project = this.state.remoteSim.project;
    let remoteOutputs = this.state.remoteSim.outputs.outputs;

    let outputs: Outputs = null;
    if (this.state.sim !== null) {
      outputs = this.state.sim.outputs;
      console.log("outputs", outputs);
    }
    return (
      <Card className="card-outer" style={{ overflow: "auto" }}>
        <Card className="card-inner">
          <Card.Body>
            <p className="lead">
              {`These results were generated by ${project.title} on ${creation_date} using ${model_version}.`}
            </p>
            <Row className="text-center">
              {remoteOutputs.renderable.outputs.map((remoteOutput, ix) => {
                let media_type = remoteOutput.media_type;
                let output: TableOutput | BokehOutput;
                if (outputs !== null && media_type == "table") {
                  output = outputs.renderable[ix];
                } else if (outputs !== null && media_type == "bokeh") {
                  output = outputs.renderable[ix];
                }
                return (
                  <Col style={{ padding: 0 }} key={`output-${ix}`}>
                    <OverlayTrigger
                      trigger={["hover", "click"]}
                      overlay={
                        <Tooltip id={`${ix}-tooltip`}>
                          {remoteOutput.title}
                        </Tooltip>
                      }
                    >
                      {outputs !== null ? (
                        <OutputModal output={output}>
                          <img
                            style={{ objectFit: "contain" }}
                            src={remoteOutput.screenshot}
                            alt={remoteOutput.title}
                            height={500}
                            width={500}
                          />
                        </OutputModal>
                      ) : (
                        <img
                          style={{ objectFit: "contain" }}
                          src={remoteOutput.screenshot}
                          alt={remoteOutput.title}
                          height={500}
                          width={500}
                        />
                      )}
                    </OverlayTrigger>
                  </Col>
                );
              })}
            </Row>
          </Card.Body>
        </Card>
      </Card>
    );
  }
}
