# Generated by Django 2.1.7 on 2019-03-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="corerun", old_name="profile", new_name="owner"
        )
    ]
