ARG TAG
FROM distributed

ENV HOST 0.0.0.0
ENV PORT 8888
ENV DEBUG true

ENV IS_SCHEDULER True

# expose the app port
EXPOSE 80
EXPOSE 8888

RUN pip install -r requirements.txt

COPY ./api /home/api
COPY ./api/endpoints.py /home/api
COPY ./setup.py /home
RUN cd /home && pip install -e .

WORKDIR /home/api

# run the app server
CMD ["gunicorn", "--bind", "0.0.0.0:5050", "api:app", "--access-logfile", "-"]
