ARG TAG
FROM distributed

ENV HOST 0.0.0.0
ENV PORT 8888
ENV DEBUG true

ENV IS_SCHEDULER True

# expose the app port
EXPOSE 80
EXPOSE 8888

RUN pip install -r requirements.txt

RUN mkdir /home/cs_workers
COPY cs_workers /home/cs_workers
COPY setup.py /home
RUN cd /home/ && pip install -e .

WORKDIR /home

CMD ["csw", "outputs-processor", "--start"]