# Generated by Django 2.1.3 on 2018-12-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exp_num_tasks',
            field=models.IntegerField(null=True),
        ),
    ]
