# Generated by Django 2.1.5 on 2019-01-24 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_projects', to='users.Profile'),
        ),
    ]
