# Generated by Django 2.1.5 on 2019-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20190129_1942")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="app_name",
            field=models.CharField(default="temp", max_length=30),
            preserve_default=False,
        )
    ]
