# Generated by Django 2.2.1 on 2019-05-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20190328_0918")]

    operations = [
        migrations.RemoveField(model_name="project", name="inputs_style"),
        migrations.RemoveField(model_name="project", name="installation"),
        migrations.RemoveField(model_name="project", name="meta_parameters"),
        migrations.RemoveField(model_name="project", name="package_defaults"),
        migrations.RemoveField(model_name="project", name="parse_user_adjustments"),
        migrations.RemoveField(model_name="project", name="run_simulation"),
    ]
