# Generated by Django 2.1.5 on 2019-03-05 13:41

import django.contrib.postgres.fields
from django.db import migrations, models
import webapp.apps.users.models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_project_app_name")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="installation",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="package_defaults",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="parse_user_adjustments",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="run_simulation",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="server_size",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=5),
                default=webapp.apps.users.models.Project.callabledefault,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "live"),
                    ("pending", "pending"),
                    ("requires fixes", "requires fixes"),
                ],
                default="live",
                max_length=32,
            ),
        ),
    ]
