# Generated by Django 2.1.7 on 2019-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20190305_0841")]

    operations = [
        migrations.RemoveField(model_name="project", name="app_name"),
        migrations.AddField(
            model_name="project",
            name="input_type",
            field=models.CharField(
                choices=[("paramtools", "paramtools"), ("taxcalc", "taxcalc")],
                default="paramtools",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="permission_type",
            field=models.CharField(
                choices=[("default", "default"), ("sponsored", "sponsored")],
                default="default",
                max_length=32,
            ),
        ),
    ]
