# Generated by Django 2.1.5 on 2019-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20190305_0841")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "live"),
                    ("pending", "pending"),
                    ("updating", "updating"),
                    ("requires fixes", "requires fixes"),
                ],
                default="live",
                max_length=32,
            ),
        )
    ]
