# Generated by Django 2.2.6 on 2019-10-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_project_listed")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cluster_type",
            field=models.CharField(default="single-core", max_length=32),
        )
    ]
