# Generated by Django 2.1.7 on 2019-03-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20190313_1530")]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="profile", new_name="owner"
        )
    ]
