# Generated by Django 2.1.7 on 2019-03-13 22:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0007_auto_20190313_1531")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="meta_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        )
    ]
