# Generated by Django 2.2.6 on 2019-12-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_project_cluster_type")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sponsor_message",
            field=models.CharField(blank=True, max_length=10000, null=True),
        )
    ]
