# Generated by Django 2.2.6 on 2019-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0008_project_sponsor_message")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pay_per_sim",
            field=models.BooleanField(default=True),
        )
    ]
