# Generated by Django 3.0.3 on 2020-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0009_project_pay_per_sim")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "live"),
                    ("updating", "updating"),
                    ("pending", "pending"),
                    ("requires fixes", "requires fixes"),
                ],
                default="live",
                max_length=32,
            ),
        )
    ]
