# Generated by Django 3.0.3 on 2020-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0010_auto_20200319_0854")]

    operations = [
        migrations.RemoveField(model_name="project", name="server_size"),
        migrations.AddField(
            model_name="project",
            name="cpu",
            field=models.DecimalField(
                decimal_places=1, default=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="memory",
            field=models.DecimalField(
                decimal_places=1, default=6, max_digits=5, null=True
            ),
        ),
    ]
