# Generated by Django 3.0.3 on 2020-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0011_auto_20200506_0928")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="repo_tag",
            field=models.CharField(default="master", max_length=32),
        )
    ]
