# Generated by Django 3.0.6 on 2020-05-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0012_project_repo_tag")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="latest_tag",
            field=models.CharField(max_length=64, null=True),
        )
    ]
