# Generated by Django 3.0.8 on 2020-08-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_project_server_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visualization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("oneliner", models.CharField(max_length=10000)),
                ("description", models.CharField(max_length=10000)),
                ("function_name", models.CharField(max_length=255)),
                (
                    "software",
                    models.CharField(
                        choices=[("dash", "Dash"), ("bokeh", "Bokeh")], max_length=64
                    ),
                ),
                ("requires_server", models.BooleanField()),
                ("is_live", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "live"),
                            ("updating", "updating"),
                            ("staging", "staging"),
                            ("requires fixes", "requires fixes"),
                        ],
                        default="live",
                        max_length=32,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="users.Project",
                    ),
                ),
            ],
        ),
    ]
