# Generated by Django 3.0.10 on 2020-09-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20200904_1054"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deployment", old_name="tag", new_name="tag_deprecated",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="latest_tag",
            new_name="latest_tag_deprecated",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="staging_tag",
            new_name="staging_tag_deprecated",
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_tag", models.CharField(max_length=64, null=True)),
                (
                    "cpu",
                    models.DecimalField(
                        decimal_places=1, default=2, max_digits=5, null=True
                    ),
                ),
                (
                    "memory",
                    models.DecimalField(
                        decimal_places=1, default=6, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=django.db.models.deletion.CASCADE,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="users.Project",
                    ),
                ),
            ],
        ),
    ]
