# Generated by Django 3.0.8 on 2020-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_visualization"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_model",
            field=models.BooleanField(default=True),
        ),
    ]
