# Generated by Django 3.0.6 on 2020-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_project_has_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="has_model",),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "live"),
                    ("updating", "updating"),
                    ("pending", "pending"),
                    ("staging", "staging"),
                    ("requires fixes", "requires fixes"),
                ],
                default="live",
                max_length=32,
            ),
        ),
        migrations.DeleteModel(name="Visualization",),
    ]
