# Generated by Django 3.0.8 on 2020-08-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20200812_1959"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="callable_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tech",
            field=models.CharField(
                choices=[
                    ("python-paramtools", "Python-ParamTools"),
                    ("dash", "Dash"),
                    ("bokeh", "Bokeh"),
                ],
                default="python-paramtools",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="RunningDeployment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=150, null=True)),
                ("tag", models.CharField(max_length=64, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_deployments",
                        to="users.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmbedApproval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=32)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embed_approvals",
                        to="users.Profile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embed_approvals",
                        to="users.Project",
                    ),
                ),
            ],
        ),
    ]
