# Generated by Django 3.0.9 on 2020-08-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200814_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningdeployment',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='runningdeployment',
            name='embed_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_deployments', to='users.EmbedApproval'),
        ),
        migrations.AddField(
            model_name='runningdeployment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_deployments', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='runningdeployment',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
