# Generated by Django 3.0.10 on 2020-09-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20200911_1433"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="status",),
    ]
