# Generated by Django 3.0.10 on 2020-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tech",
            field=models.CharField(
                choices=[
                    ("python-paramtools", "Python-ParamTools"),
                    ("dash", "Dash"),
                    ("bokeh", "Bokeh"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
