# Generated by Django 3.0.9 on 2020-08-24 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200824_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningdeployment',
            name='last_loaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
