# Generated by Django 3.0.10 on 2020-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_auto_20200928_1811"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="app_location",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
