# Generated by Django 3.0.9 on 2020-08-24 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_runningdeployment_last_loaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('last_loaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('tag', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('terminated', 'Terminated')], default='creating', max_length=32)),
                ('embed_approval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='users.EmbedApproval')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='users.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='users.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='RunningDeployment',
        ),
    ]
