# Generated by Django 3.0.9 on 2020-08-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_auto_20200824_1753"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deployment", old_name="last_loaded_at", new_name="last_load_at",
        ),
        migrations.AddField(
            model_name="deployment",
            name="last_ping_at",
            field=models.DateTimeField(null=True),
        ),
    ]
