# Generated by Django 3.0.11 on 2021-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_project_app_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="social_image_link",
            field=models.URLField(null=True),
        ),
    ]
