# Generated by Django 3.0.9 on 2020-08-26 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_auto_20200826_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="last_ping_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
