# Generated by Django 3.0.13 on 2021-03-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_project_social_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="access_token",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="access_token_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="cluster_password",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="version",
            field=models.CharField(default="v0", max_length=32),
            preserve_default=False,
        ),
    ]
