# Generated by Django 3.0.14 on 2021-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_project_embed_background_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="access_token",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="access_token_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="cluster_password",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="version",
            field=models.CharField(default="v0", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cluster",
            name="viz_host",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="version",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
