# Generated by Django 3.0.13 on 2021-03-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_auto_20210321_2004"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="version",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
