# Generated by Django 3.0.14 on 2021-06-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_auto_20210515_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="use_iframe_resizer",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
