# Generated by Django 3.0.9 on 2020-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_auto_20200827_1547"),
    ]

    operations = [
        migrations.RemoveField(model_name="cluster", name="access_token",),
        migrations.AddField(
            model_name="cluster",
            name="jwt_secret",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
