# Generated by Django 3.0.9 on 2020-08-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_auto_20200829_2134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="jwt_secret",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
