# Generated by Django 3.0.14 on 2021-08-28 16:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_auto_20210620_1934"),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_build_id", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("cancelled_at", models.DateTimeField(null=True)),
                (
                    "provider_data",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("building", "Building"),
                            ("testing", "Testing"),
                            ("pushing", "Pushing"),
                            ("cancelled", "Cancelled"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="builds",
                        to="users.Project",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="build",
            constraint=models.UniqueConstraint(
                fields=("project", "cluster_build_id"), name="unique_project_build"
            ),
        ),
    ]
