# Generated by Django 3.0.14 on 2021-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_auto_20210917_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="failed_at_stage",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("building", "Building"),
                    ("testing", "Testing"),
                    ("pushing", "Pushing"),
                    ("cancelled", "Cancelled"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
