# Generated by Django 3.0.14 on 2021-09-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_auto_20210828_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="build",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tag",
                to="users.Build",
            ),
        ),
    ]
