# Generated by Django 3.2.8 on 2021-10-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_auto_20211012_1327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="failed_at_stage",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("building", "Building"),
                    ("testing", "Testing"),
                    ("staging", "Staging"),
                    ("cancelled", "Cancelled"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("building", "Building"),
                    ("testing", "Testing"),
                    ("staging", "Staging"),
                    ("cancelled", "Cancelled"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
